export const LAYOUT_PROJECTION_MODES = {
  RADIAL: 'radial',
  HYPERBOLIC: 'hyperbolic',
  WALRUS_3D: 'walrus-3d',
};

export const DEFAULT_LAYOUT_PROJECTION_MODE = LAYOUT_PROJECTION_MODES.RADIAL;
export const DEFAULT_HYPERBOLIC_PROJECTION_STRENGTH = 0.65;
