export const TIMELINE_CONSTANTS = {
    UNIT_DURATION_MS: 1000,
    SCRUB_THROTTLE_MS: 16,
    DEFAULT_SEGMENT_INDEX: -1,
    DEFAULT_PROGRESS: 0,
    MIN_PROGRESS: 0,
    MAX_PROGRESS: 1,
    DEFAULT_TREE_IN_SEGMENT: 1,
    DEFAULT_TREES_IN_SEGMENT: 1,
    INDEX_OFFSET_UI: 1,
};

export const TIMELINE_THEME = {
    connectionWidth: 4,
    connectionHoverWidth: 6,
    connectionSelectionWidth: 8,
    connectionSelectionRGB: [5, 150, 105],
    connectionHoverRGB: [128, 128, 128],
    connectionNeutralRGB: [217, 119, 6],
    stripTrackRGB: [217, 119, 6],
    stripTrackAlpha: 230,
    stripTrackWidth: 4,
    anchorStrokeWidth: 3,
    anchorFillRGB: [240, 240, 245],
    anchorStrokeRGB: [60, 60, 80],
    anchorRadiusVar: 7,
    anchorDenseThresholdPx: 18,
    anchorTickRGB: [60, 60, 80],
    anchorTickAlpha: 180,
    anchorTickWidth: 2,
    activeAnchorTickWidth: 4,
    separatorRGB: [0, 0, 0],
    separatorWidthMax: 2,
    separatorWidthMin: 1,
    separatorAlpha: 56,
    separatorDenseAlpha: 24,
    scrubberCoreRGB: [64, 128, 255],
    gapDefault: 6,
    transitionGap: 3,
    paddingX: 8,
    paddingY: 0
};
