import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    environment: 'node',
    include: [
      'test/AdaptiveScaling.test.js',
      'test/ComparisonGeometryUtils.test.js',
      'test/ComparisonModeRenderer.test.js',
      'test/ComplexDataLayer.test.js',
      'test/ConnectorGeometryBuilder.test.js',
      'test/ConnectorIntegration.test.js',
      'test/ComparisonUtils.test.js',
      'test/DeckGLTreeAnimationController.worker.test.js',
      'test/DeckGLContext.test.js',
      'test/GeometryHelperCentralization.test.js',
      'test/ActiveTreeListSelector.test.js',
      'test/LayoutWorkerMetadata.test.js',
      'test/LayoutCacheKey.test.js',
      'test/LayoutFactoryContract.test.js',
      'test/InteractionHandlers.test.js',
      'test/MSADeckGLViewerLifecycle.test.js',
      'test/NodeLayers.test.js',
      'test/NormalizedRenderContract.test.js',
      'test/ProjectionDataContract.test.js',
      'test/RadialTreeGeometry.test.js',
      'test/RadialTreeLayout.test.js',
      'test/RealDataIntegration.test.js',
      'test/RealDataScaling.test.js',
      'test/RenderContractStatic.test.js',
      'test/SplitIdentity.test.js',
      'test/SpatialBounds.test.js',
      'test/SpatialLayout.test.js',
      'test/scaleUtils.test.js',
      'test/moved-subtree-recurrence.test.js',
      'test/subtreeConnectorBuilder.test.js',
      'test/taxa-coloring.test.js',
      'test/TidyTreeLayout.test.js',
      'test/TreeInterpolatorLabelRadius.test.js',
      'test/TimelineSegmentTooltip.test.js',
      'test/ViewportManager.test.js',
      'test/ViteConfig.test.ts',
      'test/VelocityNormalizer.test.js',
      'test/WebGLTreeAnimationController.test.js',
      'test/domain/**/*.test.{js,ts}',
      'test/integration/**/*.test.{js,ts}',
    ],
  }
});
