export const TIMELINE_CONSTANTS = {
    UNIT_DURATION_MS: 1000,
    MIN_ZOOM_MS: 100,
    ZOOM_PERCENTAGE_UI: 0.3,
    TIMELINE_HEIGHT: '35px',
    MAX_ZOOM_FACTOR: 2,
    SCRUB_THROTTLE_MS: 16,
    SCRUB_END_TIMEOUT_MS: 500,
    DEFAULT_TREE_INDEX: 0,
    DEFAULT_SEGMENT_INDEX: -1,
    DEFAULT_PROGRESS: 0,
    MIN_PROGRESS: 0,
    MAX_PROGRESS: 1,
    DEFAULT_TREE_IN_SEGMENT: 1,
    DEFAULT_TREES_IN_SEGMENT: 1,
    INDEX_OFFSET_UI: 1,
    MAX_TOOLTIP_LEAVES: 5,
    DURATION_COMPLEXITY_WEIGHT: 0.6,
    EDGE_COMPLEXITY_WEIGHT: 0.4,
    DEFAULT_COMPLEXITY: 0.5,
    DEFAULT_MAX_EDGES: 15,
    FALLBACK_MAX_EDGES: 10,
};

export const TIMELINE_THEME = {
    connectionWidth: 4,
    connectionHoverWidth: 6,
    connectionSelectionWidth: 8,
    connectionSelectionRGB: [64, 128, 255],
    connectionHoverRGB: [128, 128, 128],
    connectionNeutralRGB: [100, 100, 100],
    anchorStrokeWidth: 3,
    anchorFillRGB: [240, 240, 245],
    anchorStrokeRGB: [60, 60, 80],
    anchorRadiusVar: 7,
    separatorRGB: [0, 0, 0],
    separatorWidth: 5,
    scrubberCoreRGB: [64, 128, 255],
    gapDefault: 6,
    paddingX: 8,
    paddingY: 0
};
