export const SPR_MOVE_EVENT_TABLE_COPY = {
  searchLabel: 'Search SPR moves',
  searchPlaceholder: 'Search SPR moves by taxa, window range, pivot edge, attachment...',
  selectedValueLabel: 'Value shown',
  selectedValueChangePath: 'Change in Geometry & Labels > Branch Value for Labels & SPR Analytics',
  subtreeValueFilterLabel: 'Filter SPR moves by moved-split selected-value category',
  contextValueFilterLabel: 'Filter SPR moves by nearest-parent selected-value category',
  branchValueThresholdLabel: 'Selected-value threshold',
  branchValueThresholdInputLabel: 'Selected branch value threshold',
  clearSearchLabel: 'Clear SPR move search',
  noSearchResults: 'No SPR moves match these filters.',
  noMovements: 'No SPR moves available for this dataset.',
  branchValueFilters: {
    allSubtree: 'All moved-split values',
    allContext: 'All nearest-parent values',
    bothHigh: '{target}: Source and target >= {threshold}',
    mixed: '{target}: one side >= {threshold}',
    low: '{target}: Source and target < {threshold}',
    missing: '{target}: missing',
  },
  branchValueClasses: {
    bothHigh: 'moved-split values both >= {threshold}',
    mixed: 'moved-split one value >= {threshold}',
    low: 'moved-split values both < {threshold}',
    missing: 'moved-split value missing',
  },
  branchValueRows: {
    movedSubtree: 'Moved split',
    attachmentSupport: 'Attachment support',
    parentBranch: 'Nearest parent',
  },
  columns: {
    movement: 'SPR Move',
    movedSubtree: 'Moved Subtree',
    pivot: 'Pivot edge',
    sourceAttachment: 'Source attachment',
    targetAttachment: 'Target attachment',
    branchValue: 'Selected Value',
    steps: 'Steps',
    metrics: 'Pair Distance',
  },
  metrics: {
    rfDistance: 'RF Distance',
    weightedRf: 'Weighted RF',
  },
  minWidthClassName: 'min-w-[1120px]',
};
