export const SPR_MOVE_EVENT_TABLE_COPY = {
  searchLabel: 'Search movements',
  searchPlaceholder: 'Search movements by taxa, pivot, from/to, branch value...',
  subtreeValueFilterLabel: 'Filter movements by moved-subtree branch value category',
  contextValueFilterLabel: 'Filter movements by placement-context branch value category',
  branchValueThresholdLabel: 'Value threshold',
  branchValueThresholdInputLabel: 'Branch value threshold',
  clearSearchLabel: 'Clear movement search',
  noSearchResults: 'No movements match these filters.',
  noMovements: 'No movements available for this dataset.',
  branchValueFilters: {
    allSubtree: 'All subtree values',
    allContext: 'All placement context values',
    bothHigh: '{target} both >= {threshold}',
    mixed: '{target} one >= {threshold}',
    low: '{target} both < {threshold}',
    missing: '{target} missing',
  },
  branchValueClasses: {
    bothHigh: 'moved subtree values both >= {threshold}',
    mixed: 'moved subtree one value >= {threshold}',
    low: 'moved subtree values both < {threshold}',
    missing: 'moved subtree value missing',
  },
  branchValueRows: {
    movedSubtree: 'Moved subtree',
    nearestAncestor: 'Placement context',
  },
  columns: {
    movement: 'Movement',
    movedSubtree: 'Moved Subtree',
    pivot: 'Pivot Edge',
    from: 'From Edge',
    to: 'To Edge',
    branchValue: 'Branch Value',
    steps: 'Steps',
    metrics: 'Metrics',
  },
  metrics: {
    hops: 'Hops',
    length: 'Length',
    rfDistance: 'RF Distance',
    weightedRf: 'Weighted RF',
  },
  minWidthClassName: 'min-w-[940px]',
};
